general:
  vulnerabilities:
    - CVE-2019-1010022 # Red Hat Product Security does not consider this to be a vulnerability. See https://access.redhat.com/security/cve/cve-2019-1010022
    - CVE-2022-25648 # Under investigation. See https://access.redhat.com/security/cve/cve-2022-25648
    - CVE-2024-24790 # golang vulnerability in stdlib, jobber is not affected
