<?php
// Do not edit this file directly! It is automatically generated after every container start.
class DATABASE_CONFIG {
    public $default = [
        'datasource' => 'Database/Mysql',
        'persistent' => false,
        'host' => '{{ MYSQL_HOST }}',
        'login' => '{{ MYSQL_LOGIN }}',
        'port' => {{ MYSQL_PORT }},
        'password' => '{{ MYSQL_PASSWORD }}',
        'database' => '{{ MYSQL_DATABASE }}',
        'prefix' => '',
        'encoding' => 'utf8',
        'settings' => ['time_zone' => '"+00:00"'],
    ];
}
